### ISSUE TITLE
Hello, the cloudflare R2 destination path is wrong

### ISSUE THREAD

**Issue by koobai** [ryand56/r2-upload-action#260]
Hello, there is a new problem, I set the upload root folder source-dir: koobaiblog upload, after uploading to cloudflare R2 files are not in the root directory, but automatically create a new "/" folder. I didn't set destination-dir either

<img width="720" alt="image" src="https://github.com/ryand56/r2-upload-action/assets/50470569/80e41dc7-4b55-418e-b28f-feef9a33ab1f">

**Comment by ryand56** [comment]
Yeah, I'll fix that shortly
