### ISSUE TITLE
Write EPIPE Error

### ISSUE THREAD

**Issue by bagusnl** [ryand56/r2-upload-action#286]
Hi, sorry for bothering you again about issue in the r2 upload action

We've recently starting to use more of our CDN with the use of this action as a way to sync the content from GitHub to our bucket. But we are not sure why since last week our sync action keeps failing while re-uploading our full nupkg file (around ~45MB in size). Though, if the bucket were from a clean state (all files deleted and action is triggered), the error disappears.

Also for a note, we recently enables public access to our r2 bucket, but I'm not sure if that's the problem.

Here is the repository last failed action log https://github.com/neon-nyan/CollapseLauncher-ReleaseRepo/actions/runs/5950552117/job/16138558088

Edit:
- Here is the statistics on the bucket itself
![image](https://github.com/ryand56/r2-upload-action/assets/28079733/e2208cfc-61e7-4cc8-9225-d46d0c239fa5)
Class A requests number doesn't seem to be the problem as its still far from the free limit Cloudflare give to a bucket

**Comment by ryand56** [comment]
This is happening because the S3 library cannot handle the file uploading for some reason, not a problem with this GitHub action :(

**Comment by bagusnl** [comment]
Ah, got it. I will ask Cloudflare on why this is happening, thank you.

On the other question, I thought for a file that is already exist in the bucket it wont get re-uploaded again?

**Comment by bagusnl** [comment]
Also, is it possible to keep uploading other file even if that one file got an error?

**Comment by ryand56** [comment]
If the files contents haven't changed, it shouldn't be reuploaded again. I'll make an option to skip the files that can't be uploaded if there is an error.

**Comment by bagusnl** [comment]
It's kinda why I'm quite confused on why it gives that error. Because that file that gives the error is the one that is already inside the bucket and it's unchanged

**Comment by ryand56** [comment]
It relates to something else on Cloudflare's end or the S3 library.
