### ISSUE TITLE
endpoint issues using specific jurisdiction

### ISSUE THREAD

**Issue by use-to** [ryand56/r2-upload-action#454]
There is a new feature in R2 letting you choose a jurisdiction / location where your bucket is stored.
For that purpose cloudflare added a new subdomain (for `eu` in this case) inbetween.

| Normal:
`https://<id>.r2.cloudflarestorage.com/<bucket-name>`

| Custom Jurisdiction:
`https://<id>.eu.r2.cloudflarestorage.com/<bucket-name>`

# Settings cloudflare
![image](https://github.com/user-attachments/assets/57c744d2-ed23-44b6-a138-b8e8b999af25)

**Comment by ryand56** [comment]
This was added already, see #434.
